### ISSUE TITLE
The command setup

### ISSUE THREAD

**Issue by victordit** [worlddb/world.db.tools#1]
Hi, i write the following new part of readme for documentation (for setup command):  the current example command return a error because try open the file "world.db" but this not exits, i'ts should be the path.

Thanks

### `setup` Command

~~~
NAME
    setup - Create DB schema 'n' load all world data. The data are txt files under [./setups](https://github.com/openmundi/world.db/tree/master/setups) 

SYNOPSIS
    worlddb [global options] setup [command options] NAME

COMMAND OPTIONS
    -i, --include=PATH  - World data path (default: .)

EXAMPLES
    - Outside directory [world.db](https://github.com/openmundi/world.db)
    - - worlddb setup --include=world.db/ all #(create and load all world data)
    - - worlddb setup us --include=world.db/ #(create and load us data)

    - Inside directory [world.db](https://github.com/openmundi/world.db)
    - - worlddb setup all  #(create and load all world data)

**Comment by geraldb** [comment]
Thanks. if you have troube building the world.db, please send your questions to the [forum](groups.google.com/group/openmundi).  Your comments/addition might be great for a new F.A.Q. or troubleshooting page. Cheers.

**Comment by victordit** [comment]
Thanks @geraldb, the link to forum return not found, is the forum on Google groups?

**Comment by geraldb** [comment]
@victordit  Sorry. Thanks. Yes, it's a google group. Fixed the link. Cheers.
